esphome:
  name: allbot-vr204
  friendly_name: ALLBOT VR204

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source:
      type: local
      path: ../components
    components: [allbot]

i2c:
  sda: GPIO21
  scl: GPIO22
  frequency: 400kHz

pca9685:
  - id: pca
    address: 0x40
    frequency: 50Hz

output:
  - platform: ledc
    id: buzzer_out
    pin: GPIO13
    frequency: 1000Hz
  - platform: pca9685
    pca9685_id: pca
    id: pwm_hip_l
    channel: 0
  - platform: pca9685
    pca9685_id: pca
    id: pwm_hip_r
    channel: 1
  - platform: pca9685
    pca9685_id: pca
    id: pwm_ankle_r
    channel: 2
  - platform: pca9685
    pca9685_id: pca
    id: pwm_ankle_l
    channel: 3

rtttl:
  id: buzzer
  output: buzzer_out

allbot:
  id: bot
  servos:
    - id: hip_l
      output: pwm_hip_l
      initial_angle: 90
      flipped: true
    - id: hip_r
      output: pwm_hip_r
      initial_angle: 90
      flipped: false
    - id: ankle_r
      output: pwm_ankle_r
      initial_angle: 90
      flipped: false
    - id: ankle_l
      output: pwm_ankle_l
      initial_angle: 90
      flipped: true
  actions:
    walk_forward:
      - duration: 200ms
        moves: [{servo: hip_l, angle: 130}, {servo: hip_r, angle: 40}]
      - duration: 200ms
        moves: [{servo: ankle_l, angle: 45}]
      - duration: 200ms
        moves: [{servo: ankle_r, angle: 135}]
      - duration: 200ms
        moves: [{servo: ankle_l, angle: 90}]
      - duration: 200ms
        moves: [{servo: ankle_r, angle: 90}]
      - duration: 200ms
        moves: [{servo: hip_l, angle: 90}, {servo: hip_r, angle: 90}]

    walk_backward:
      - duration: 200ms
        moves: [{servo: hip_l, angle: 130}, {servo: hip_r, angle: 40}]
      - duration: 200ms
        moves: [{servo: ankle_l, angle: 135}]
      - duration: 200ms
        moves: [{servo: ankle_r, angle: 45}]
      - duration: 200ms
        moves: [{servo: ankle_l, angle: 90}]
      - duration: 200ms
        moves: [{servo: ankle_r, angle: 90}]
      - duration: 200ms
        moves: [{servo: hip_l, angle: 90}, {servo: hip_r, angle: 90}]

    walk_left:
      - duration: 100ms
        moves: [{servo: ankle_l, angle: 45}]
      - duration: 100ms
        moves: [{servo: ankle_r, angle: 135}]
      - duration: 100ms
        moves: [{servo: ankle_l, angle: 90}]
      - duration: 100ms
        moves: [{servo: ankle_r, angle: 90}]

    walk_right:
      - duration: 100ms
        moves: [{servo: ankle_r, angle: 45}]
      - duration: 100ms
        moves: [{servo: ankle_l, angle: 135}]
      - duration: 100ms
        moves: [{servo: ankle_r, angle: 90}]
      - duration: 100ms
        moves: [{servo: ankle_l, angle: 90}]

    look_left:
      - duration: 200ms
        moves: [{servo: hip_l, angle: 135}, {servo: hip_r, angle: 45}]
      - duration: 100ms
      - duration: 200ms
        moves: [{servo: hip_l, angle: 90}, {servo: hip_r, angle: 90}]

    look_right:
      - duration: 200ms
        moves: [{servo: hip_l, angle: 45}, {servo: hip_r, angle: 135}]
      - duration: 100ms
      - duration: 200ms
        moves: [{servo: hip_l, angle: 90}, {servo: hip_r, angle: 90}]

    scared:
      - duration: 100ms
        moves: [{servo: ankle_l, angle: 45}, {servo: ankle_r, angle: 45}]
      - duration: 100ms
        moves: [{servo: ankle_l, angle: 135}, {servo: ankle_r, angle: 135}]
      - duration: 100ms
        moves: [{servo: ankle_l, angle: 45}, {servo: ankle_r, angle: 45}]
      - duration: 100ms
        moves: [{servo: ankle_l, angle: 135}, {servo: ankle_r, angle: 135}]
      - duration: 100ms
        moves: [{servo: ankle_l, angle: 90}, {servo: ankle_r, angle: 90}]

api:
  actions:
    - action: walk_forward
      then: [allbot.run_action: {id: bot, action: walk_forward}]
    - action: walk_backward
      then: [allbot.run_action: {id: bot, action: walk_backward}]
    - action: walk_left
      then: [allbot.run_action: {id: bot, action: walk_left}]
    - action: walk_right
      then: [allbot.run_action: {id: bot, action: walk_right}]
    - action: look_left
      then: [allbot.run_action: {id: bot, action: look_left}]
    - action: look_right
      then: [allbot.run_action: {id: bot, action: look_right}]
    - action: scared
      then:
        - allbot.run_action: {id: bot, action: scared}
        - rtttl.play: {rtttl: "scared:d=16,o=6,b=180:c,e,g,c7,e,g,c7"}
    - action: chirp
      then:
        - rtttl.play: {rtttl: "chirp:d=32,o=7,b=180:c,c,c"}
    - action: stop
      then:
        - allbot.stop: {id: bot}
        - rtttl.stop:
